paths:
  uploads: public/uploads
  static: public
collections_config:
  pages:
    path: src/pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  blog:
    path: src/content/blog
    icon: event_available
    disable_url: false
    preview:
      text:
      subtext:
        - key: author
      icon:
      icon_color:
      icon_background_color:
      image:
      metadata:
      gallery:
        text:
        icon:
        icon_color:
        icon_background_color:
        background_color:
        image:
          - key: image.src
        fit: cover
    sort_options:
      - key: title
        order: ascending
        label:
      - key: publishDate
        order: ascending
        label:
    _inputs:
      $.draft:
        type: switch
        cascade: true
      $.publishDate:
        type: datetime
        cascade: true
      $.image.src:
        type: image
        cascade: true
      $.title:
        type: text
        options:
          icon:
          empty_type:
          required: true
          required_message: Blog post requires a title!
          min_length:
          min_length_message:
          max_length:
          max_length_message:
          pattern:
          pattern_message:
        cascade: true
    disable_add: false
    disable_add_folder: true
    disable_file_actions: true
  team:
    path: src/content/team
    icon: emoji_people
    disable_url: false
    preview:
      text:
      subtext:
        - key: title
      icon:
      icon_color:
      icon_background_color:
      image:
      metadata:
      gallery:
        text:
        icon:
        icon_color:
        icon_background_color:
        background_color:
        image:
          - key: avatar.src
        fit: padded
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: false
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
